debug: true
dialect: postgres
connectionString: postgresql://postgres:secret@localhost:54321/gateway?sslmode=disable&client_encoding=UTF8
maxIdleConnections: 10
maxOpenConnections: 30 # 30–50 is good for most services
maxLifetimeSeconds: 300
maxIdleTimeSeconds: 60